export const products = [
  {
    id: 1,
    name: "Waffle with berries",
    category: "Waffles",
    price: 6.99,
    Image: "img/waffles.jpg",
  },
  {
    id: 2,
    name: "Chocolate Brownies",
    category: "Brownies",
    price: 4.89,
    Image: "img/brownies.jpg",
  },
  {
    id: 3,
    name: "Velvet Cake",
    category: "Cake",
    price: 9.00,
    Image: "img/cake.jpg",
  },
  {
    id: 4,
    name: "vanilla Pancake",
    category: "pancake",
    price: 4.50,
    Image: "img/pancake.jpg",
  },
  {
    id: 5,
    name: "Chocolate smoothie",
    category: "Smoothie",
    price: 4.50,
    Image: "img/chocolate smoothie.jpg",
  },
  {
    id: 6,
    name: "Kiwi Drink",
    category: "Drink",
    price: 4.50,
    Image: "img/drink.jpg",
  },
  {
    id: 7,
    name: "Burger",
    category: "burgers",
    price: 4.50,
    Image: "img/burger.jpg",
  },
  {
    id: 8,
    name: " vanilla Ice Cream",
    category: "Ice-Cream",
    price: 4.50,
    Image: "img/icecream.jpg",
  },
  {
    id: 9,
    name: "Chicken Sandwich",
    category: "Sandwich",
    price: 4.50,
    Image: "img/sandwich2.jpg",
  },
  {
    id: 10,
    name: "Chocolate pancake",
    category: "pancake",
    price: 4.50,
    Image: "img/chocolate pankcake.jpg",
  },
];
